### ISSUE TITLE
ClassNotFoundException : DateTimeFormatter

### ISSUE THREAD

**Issue by jhomzbenito** [blackmo18/kotlin-grass#10]
**ERROR**
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/[app_name]/base.apk"],nativeLibraryDirectories=[/data/app/[app_name]/lib/arm, /system/lib, /vendor/lib]]

**Environment**
 - kotlin-csv version 0.11.0
 - java version  java8
 - OS: Windows/Android

**Comment by blackmo18** [comment]
Hi @jhomzbenito, what is the min target Version of your android target? DateTimeFormatter is added to API level 26.

**Comment by Goopher** [comment]
@blackmo18, would it be possible to fall back to the threetenbp library for Android if java.time is not available? Or is that not that easy to implement?

**Comment by bugrayetkinn** [comment]
SimpleDateFormat you can use.

**Comment by blackmo18** [comment]
> @blackmo18, would it be possible to fall back to the threetenbp library for Android if java.time is not available? Or is that not that easy to implement?

@Goopher My first thought would be,  separate  the support for java 8 date and time APIs as library plugin.

And provide an api to easily plug user's custom parsing. Which i think the current track is nearly there already there or so .

I would appreciate  open  a request or recieve a pull request.

😁👍

**Comment by blackmo18** [comment]
Java 8 Date Time is now optional, See [release  0.8.0](https://github.com/blackmo18/kotlin-grass/releases/tag/v0.8.0)
