### ISSUE TITLE
import csv throw NullPointerException.

### ISSUE THREAD

**Issue by Jacky-YC** [blackmo18/kotlin-grass#26]
**Describe the bug**

**To Reproduce**
NPE

**Expected behavior**
Test failed
java.lang.NullPointerException
	at io.blackmo18.kotlin.grass.pot.Root.createObject(Root.kt:70)
	at io.blackmo18.kotlin.grass.pot.Stem.harvestData(Stem.kt:48)
	at io.blackmo18.kotlin.grass.pot.Plant.harvest(Plant.kt:42)

**Environment**
 - kotlin-csv version：1.2.0 、 0.15.2
 - java version: 17
 - OS: Windows11\MacOS\Windows10

**Screenshots**
![image](https://user-images.githubusercontent.com/42370375/147377219-5bc45463-b907-4f88-b712-b1f371ef5771.png)
![image](https://user-images.githubusercontent.com/42370375/147377222-c16a1665-a8fa-4e7a-9378-570e935211a2.png)

**Comment by Jacky-YC** [comment]
id,product_type,fastone_region,fastone_model,price
1,VM,NORTH1,p1.c1.2,0.5916

**Comment by Jacky-YC** [comment]
data class ProductDto(
	val id: Long,
	val productType: ProductType,
	val fastoneRegion: Region,
	val fastoneModel: String,
	val price: BigDecimal
)

**Comment by blackmo18** [comment]
@Jacky-YC 

can you create a simple repo to try this one?

**Comment by Jacky-YC** [comment]
yes, i'm sorry! i try registry my custom data type is ok!

**Comment by Jacky-YC** [comment]
The tests have passed.

**Comment by Jacky-YC** [comment]
Very useful class library, thanks to the author

**Comment by blackmo18** [comment]
I was running the test a while ago, it passed. So I was thinking, maybe custom name.  It seems It was OK on your end now.  I will be closing this issue then.
